#
# Configuration
#
group: deprecated-2017Q2
sudo: required
dist: trusty

notifications:
  email: true

cache:
  yarn: true
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - google-chrome-stable
      - lib32stdc++6
      - lib32z1

# branches:
#   only:
#     - master

#
# Build Lifecycle:
#

before_install:
  - nvm install --lts
  - node --version
  - npm install -g yarn@latest cordova@6.4.0 ionic@3.2.0

install: yarn

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run test-ci  # unit tests
  - npm run e2e      # run e2e tests against ionic

after_success:
  # Send coverage info off to cloud ppl
  - ./node_modules/.bin/codecov
